artifact_uri: file:///E:/YandexDisk/Notebooks/test_task/runs/mlflow/184463932476833991/fa057e449fcf4fc78ac220a92e6f4f48/artifacts
end_time: null
entry_point_name: ''
experiment_id: '184463932476833991'
lifecycle_stage: active
run_id: fa057e449fcf4fc78ac220a92e6f4f48
run_name: training_l
run_uuid: fa057e449fcf4fc78ac220a92e6f4f48
source_name: ''
source_type: 4
source_version: ''
start_time: 1732184696666
status: 1
tags: []
user_id: pluxa
